
build:
	pandoc -s -f gfm -t html5 -c ../../templates/common.css -c ../../templates/blog_style.css -B ../../templates/blog_header.html -A ../../templates/blog_footer.html -o index.html *.md

clean:
	rm index.html
